In [1]:
import numpy as np
arr1=np.array([
    [1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([
    [10,20,30],[40,50,60,],[70,80,90]])
result=np.dot(arr1,arr2)
print(result)

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]
