In [ ]:
#create an array

In [1]:
import numpy as np
x=np.array([
          [10,20,30],
          [40,50,60],
          [70,80,90]])
print(x)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [3]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
import numpy as np
x=np.array([
          [10,20,30],
          [40,50,60],
          [70,80,90]],dtype=complex)
print(x)

[[10.+0.j 20.+0.j 30.+0.j]
 [40.+0.j 50.+0.j 60.+0.j]
 [70.+0.j 80.+0.j 90.+0.j]]


In [9]:
import numpy as np
x=np.array([
          [10,20,30],
          [40,50,60],
          [70,80,90]],dtype=float)
print(x)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]


In [ ]:
zero() and ones()

In [11]:
y=np.zeros((2,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
y=np.ones((3,2))
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
z=np.ones((3,3),dtype=[('m','int'),('n','float')])
print(z)

[[(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]]


In [19]:
import numpy as np
x=np.array([
          [10,20,30],
          [40,50,60],
          [70,80,90]])
#print(x)
for i in x:
    for j in i:
        print(j,end=" ")
    print()

10 20 30 
40 50 60 
70 80 90 


In [21]:
import numpy as np
x=np.array([
          [10,20,30],
          [40,50,60],
          [70,80,90]])
print("Row 0:",x[0])

Row 0: [10 20 30]


In [25]:
import numpy as np
x=np.array([
          [10,20,30],
          [40,50,60],
          [70,80,90]])
print("Row 1:",x[1])
print("Row 2:",x[2])

Row 1: [40 50 60]
Row 2: [70 80 90]


In [27]:
print(x[0:2])

[[10 20 30]
 [40 50 60]]


In [29]:
print(x[1:])

[[40 50 60]
 [70 80 90]]


In [31]:
print(x[::-1])

[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [35]:
import numpy as np
x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
x[[0, 2]] = x[[2, 0]]
print(x)


[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [33]:
print(x[:,0])

[10 40 70]


In [41]:
x=np.array([
          [10,20,30],
          [40,50,60],
          [70,80,90]])
print("column 0:",x[:,0])
print("column 1:",x[:,1])
print("column 2:",x[:,2])

column 0: [10 40 70]
column 1: [20 50 80]
column 2: [30 60 90]
